### ISSUE TITLE
Research a library to select colors for slices if possible within our existing code

### ISSUE THREAD

**Issue by dignojrteogalbo** [cs481-ekh/s24-slice-n-dice#163]
References #32

**Comment by matthew-oberg** [comment]
Started research.

[t:90]

**Comment by matthew-oberg** [comment]
More looking around.

[t:90]

**Comment by matthew-oberg** [comment]
It seems there is no way to change just the area that is sliced, either for opacity or color, with how this is currently implemented due to Ipyvolume only allowing a single volume at a time.

It is possible that a different visualization type could be used, such as meshes, with the sliced halves being different meshes, which can be graphed differently. However, I don't believe there's a way to modify just the impression left of the slice plane.

As far as 3D slicing goes, I don't think there is any option that could reasonable replace ipyvolume, especially this late in the game. I think our best bet is to focus on 2D slices as requested by the sponsor.

Research done.
[t:30]
