### ISSUE TITLE
Research ipyvolume interactivity

### ISSUE THREAD

**Issue by matthew-oberg** [cs481-ekh/s24-slice-n-dice#94]
References #26 

 - [ ] Determine how much of the interactivity work ipyvolume will do for us

**Comment by BraydenThompson** [comment]
Ipyvolume gives us a lot of functionality and customization for our volume graphs. By default, we get the following useful features:
- Rotation
- Panning
- Zooming
- Scaling the entire graph (not the camera)
- Changing the selected range of values in the volume
- Changing the opacity of values
- Graphing multiple volumes or plots in the same output (We can use a scatter plot or similar for graphing atoms within the volume)
- Changing size / resolution of graph
- Customization of axis / labels
- Exporting of images

Ipyvolume does support the native export of animated gifs as well, but unfortunately it seems like this is limited to scatter and quiver plots, and is not compatible with volumes.  [(See here)](https://ipyvolume.readthedocs.io/en/latest/examples/animation.html) We would however be able to save a png sequence and encode it as a video manually. 

We can also customize and interact with the thorough api in code, allowing us to attach sliders and buttons to modify almost any attribute of the graph. [API docs](https://ipyvolume.readthedocs.io/en/latest/api.html#)

![Image](https://github.com/cs481-ekh/s24-slice-n-dice/assets/77991576/c20fc62c-4c0f-4b81-87b7-3a1d617bdd35)

I also encountered heavy delays on being able to run Ipyvolume due to windows compatibility issues, which I will create a task to resolve in teh future. I ended up having to use WSL in order to get widgets to render successfully 

[t:170]
